server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routesMap:
          estudiantes:
            uri: http://localhost:8090
            predicates:
              - Path=/api/student/**
          cursos:
            uri: http://localhost:9090
            predicates:
              - Path=/api/courses/**

eureka:
  client:
    register-with-eureka: false